### ISSUE TITLE
error: depends on undefined module "slicer"

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [pixeldustproject-o/android_art#1]
Hi.
I have errors:
error: art/test/Android.bp:364:1: "libtistress" depends on undefined module "slicer"
error: art/test/Android.bp:370:1: "libtistressd" depends on undefined module "slicer"
Can You guide me how to solve them?

**Comment by spezi77** [comment]
Pick this commit:
https://github.com/pixeldustproject-o/android_art/commit/0506fe1f454f6ad3f928e8c4a36fb994bd62743a
