### ISSUE TITLE
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: treating warnings as errors

### ISSUE THREAD

**Issue by rupansh** [pixeldustproject-o/android_art#2]
Warning - art/runtime/entrypoints/quick/quick_dexcache_entrypoints.cc:0: warning: relocation refers to discarded section
Fix- "LOCAL_DISABLE_FATAL_LINKER_WARNINGS := true" in some makefile which I am not sure about
have tried adding it to art/Android.mk but didn't fix
branch - o2-sdc

**Comment by spezi77** [comment]
Try again with branch o2.
